apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Release.Name }}
spec:
  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ $.Release.Name}}
