apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-back
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: okr.com
      http:
        paths:
        - path: /backend(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: app-back
              port:
                number: 8080
