apiVersion: v1
kind: Service
metadata:
  name: app-back
  labels:
    app: app-back
spec:
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: app-back
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  