name: app-back

image: rafaelduartes/app-back:latest

secret: docker-registry

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPPUtilizationPercentage: 50

service:
  internalTrafficPolicy: Cluster
  type: ClusterIP
  targetPort: 8080
  ports:
    name: http
    port: 8080
    targetPort: 8080

resources:
  enabled: true
  limits:
    cpu: 500m
    memory: 550Mi

ingress:
  host: okr.com
  enabled: true
  pathUrl: /backend(/|$)(.*)
  pathType: Prefix
  portNumber: 8080